### ISSUE TITLE
TapTap

### ISSUE THREAD

**Issue by huracani** [EDagger/Hello-World#7]
@@ -56,3 +56,6 @@ option3.addEventListener("click", function(){
 });

 generate_equation()

**Comment by piton182** [comment]
@huracani это что? случайность или я не понимаю что это такое?

**Comment by huracani** [comment]
> @huracani это что? случайность или я не понимаю что это такое?

Случайно

**Comment by piton182** [comment]
ок, нет проблем, закрой плиз в таком случае
